---
# Source: jerney-blog-app/templates/namespace.yml
apiVersion: v1
kind: Namespace
metadata:
  name: jerney
---
# Source: jerney-blog-app/templates/network-policy.yml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-allow-frontend-only
  namespace: jerney
spec:
  # 1. Target the backend application pods
  podSelector:
    matchLabels:
      app: jerney-backend # Use a value from values.yaml for flexibility
  
  policyTypes:
    - Ingress

  # 2. Whitelist: Only allow traffic from the frontend pods
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: jerney-frontend # Use a value from values.yaml for flexibility
      ports:
        - protocol: TCP
          port: 5000 # The internal network port your Node.js backend runs on
---
# Source: jerney-blog-app/templates/network-policy.yml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-allow-backend-only
  namespace: jerney
spec:
  # 1. Target the PostgreSQL database pod
  podSelector:
    matchLabels:
      app: postgres # Use a value from values.yaml for flexibility
  
  policyTypes:
    - Ingress

  # 2. Whitelist: Only allow traffic from the backend pods
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: jerney-backend # Use a value from values.yaml for flexibility
      ports:
        - protocol: TCP
          port: 5432 # The standard PostgreSQL port
---
# Source: jerney-blog-app/templates/config-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: jerney-secret
  namespace: jerney
type: Opaque
stringData: # Plain text allowed here; K8s will encode it automatically
  DB_USER: jerney_user
  DB_PASSWORD: jerney_pass_2026
  DATABASE_URL: postgres://jerney_user:jerney_pass_2026@postgres-service:5432/jerney_db
---
# Source: jerney-blog-app/templates/config-secret.yml
apiVersion: v1
kind: ConfigMap
metadata:
  name: jerney-config
  namespace: jerney
data:
  NODE_ENV: production
  PORT: 5000
  DB_HOST: postgres-service
  DB_PORT: 5432
  DB_NAME: jerney_db
---
# Source: jerney-blog-app/templates/database.yml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jerney-ebs-sc
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp3
  encrypted: "true"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
# Source: jerney-blog-app/templates/backend.yml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jerney # 
spec:
  type: ClusterIP
  ports:
    - port: 5000
  selector:
    app: jerney-backend
  template:
    spec:
      containers:
        - image: ram7800/jerney-backend:b72
---
# Source: jerney-blog-app/templates/database.yml
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: jerney
spec:
  clusterIP: None # Headless service keeps network identities stable
  ports:
    - port: 5432
  selector:
    app: postgres
---
# Source: jerney-blog-app/templates/frontend.yml
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: jerney
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jerney-frontend
  template:
    spec:
      containers:
        - image: ram7800/jerney-frontend:b72
---
# Source: jerney-blog-app/templates/backend.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerney-backend
  namespace: jerney
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jerney-backend
  template:
    metadata:
      labels:
        app: jerney-backend
    spec:
      securityContext:
        runAsNonRoot: true # Enforces that the container cannot run as UID 0 (root)
        runAsUser: 1000 # 1000 is the default non-root 'node' user built into official Node images
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: backend
          image: ram7800/jerney-backend:b72 # Update this to your Docker Hub username and image tag
          command: ["node", "src/index.js"]
          ports:
            - containerPort: 5000
              name: http-api
          securityContext:
            allowPrivilegeEscalation: false # Stops child processes from gaining root execution traits
            readOnlyRootFilesystem: true # Turns your app directory read-only to stop malicious payload injects
            capabilities:
              drop:
                - ALL
          readinessProbe:
            httpGet:
              path: /api/health # Ensure your Express/Node app has this route configured!
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: jerney-config
            - secretRef:
                name: jerney-secrets
---
# Source: jerney-blog-app/templates/frontend.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jerney-frontend
  namespace: jerney
  labels:
    app: jerney-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jerney-frontend
  template:
    metadata:
      labels:
        app: jerney-frontend
    spec:
      securityContext:
        runAsNonRoot: true # Prevents the container from starting if it runs as root
        runAsUser: 101 # Forces execution as a standard non-root user (101 is standard for nginx-unprivileged)
        runAsGroup: 101
        fsGroup: 101
      containers:
        - name: frontend
          image: ram7800/jerney-frontend:b72 # Update this to your Docker Hub username and image tag
          ports:
            - containerPort: 8080
              name: http
          securityContext:
            allowPrivilegeEscalation: false # Prevents processes from gaining more privileges than their parent
            readOnlyRootFilesystem: true # Locks the root disk down. Attackers cannot download or install malware/scripts
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5 
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: jerney-blog-app/templates/database.yml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: jerney
spec:
  serviceName: "postgres-service"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: jerney-config
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: jerney-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jerney-secret
                  key: DB_PASSWORD
          ports:
            - containerPort: 5432
              name: postgres
          # ─── DEVSECOPS BLOCK 3: VOLUMES & READ-ONLY BYPASSES ───
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data  # The physical block disk from AWS EBS
            - name: pg-run-volume
              mountPath: /var/run/postgresql       # In-memory location for database lock/socket files
            - name: pg-tmp-volume
              mountPath: /tmp

          volumes:
        - name: pg-run-volume
          emptyDir: {}
        - name: pg-tmp-volume
          emptyDir: {}
          
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi

          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)", "-d", "$(POSTGRES_DB)"]
            initialDelaySeconds: 30
            periodSeconds: 20
            
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data # Path inside container where Postgres writes data
  # ─── DYNAMIC STORAGE ARCHITECTURE ───#

  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: [ "ReadWriteOnce" ] # Only one node can read/write to this disk at a time
        storageClassName: jerney-ebs-sc # Binds directly to the StorageClass defined above
        resources:
          requests:
            storage: 10Gi # Requested disk allocation
---
# Source: jerney-blog-app/templates/ingress.yml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jerney-ingress
  namespace: jerney
  annotations:
    alb.ingress.kubernetes.io/group.name: shared-alb-group
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
spec:
  rules:
    -
      host: "myjerneyapp007.com"
      http:
        paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                 name: frontend-service
                 port:
                   number: 80
           - path: /argocd
             pathType: Prefix
             backend:
               service:
                 name: argocd-server
                 port:
                   number: 80
---
# Source: jerney-blog-app/templates/argo-app.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jerney-blog-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Devops-Raja/jerney-blog-app.git
    targetRevision: devops
    path: helm/jerney-blog-app
  destination:
    server: https://kubernetes.default.svc
    namespace: jerney
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
