apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo-ingress
  namespace: argocd
  annotations:
   {{- toYaml .Values.argo_ingress.annotations | nindent 4 }}
spec:
  rules:
    - {{- if .Values.argo_ingress.host }}
      host: {{ .Values.argo_ingress.host | quote }}
      {{- end }}
      http:
        paths:
           {{- range .Values.argo_ingress.paths }}
           - path: {{ .path }}
             pathType: Prefix
             backend:
               service:
                 name: {{ .serviceName }}
                 port:
                   number: {{ .port }}
           {{- end }}
         