{{- if .Values.argocd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.argocd.name | default "jerney-blog-app" }}
  namespace: {{ .Values.argocd.namespace | default "argocd" }}
spec:
  project: {{ .Values.argocd.project | default "default" }}
  source:
    repoURL: {{ .Values.argocd.repoURL }}
    targetRevision: {{ .Values.argocd.targetRevision }}
    path: {{ .Values.argocd.path }}
  destination:
    server: {{ .Values.argocd.destinationServer | default "https://kubernetes.default.svc" }}
    namespace: {{ .Values.argocd.targetNamespace | default "jerney" }}
  syncPolicy:
    automated:
      selfHeal: {{ .Values.argocd.syncPolicy.selfHeal | default true }}
      prune: {{ .Values.argocd.syncPolicy.prune | default true }}
{{- end }}