apiVersion: v1
kind: ConfigMap
metadata:
  name: jerney-config
  namespace: jerney
data:
  NODE_ENV: {{.Values.config.nodeEnv}}
  PORT: {{.Values.config.port}}
  DB_HOST: {{.Values.config.dbHost}}
  DB_PORT: {{.Values.config.dbPort}}
  DB_NAME: {{.Values.config.dbName}}

---
apiVersion: v1
kind: Secret
metadata:
  name: jerney-secret
  namespace: jerney
type: Opaque
stringData: # Plain text allowed here; K8s will encode it automatically
  DB_USER: {{.Values.secret.DB_USER}}
  DB_PASSWORD: {{.Values.secret.DB_PASSWORD}}
  DATABASE_URL: {{.Values.secret.DATABASE_URL}}
