apiVersion: v1
kind: ConfigMap
metadata:
  name: jerney-config
  namespace: jerney
data:
  NODE_ENV: {{.Values.config.nodeEnv | quote}}
  PORT: {{.Values.config.port | quote}}
  DB_HOST: {{.Values.config.dbHost| quote}}
  DB_PORT: {{.Values.config.dbPort | quote}}
  DB_NAME: {{.Values.config.dbName | quote}}

---
apiVersion: v1
kind: Secret
metadata:
  name: jerney-secrets
  namespace: jerney
type: Opaque
stringData: # Plain text allowed here; K8s will encode it automatically
  DB_USER: {{.Values.secret.DB_USER | quote}}
  DB_PASSWORD: {{.Values.secret.DB_PASSWORD | quote}}
  DATABASE_URL: {{.Values.secret.DATABASE_URL | quote}}
